language: python
sudo: enabled
services:
    - mysql
python:
    - "3.5"
before_install:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS wechat_ticket;'
    - mv configs.example.json configs.json
install:
    - pip install -r requirements.txt
    - mkdir /home/travis/build/ParadoxShi/wechatTicket_2018/static/img/Upload
script:
    - python manage.py test